version: "3.9"
services:
  encodecmae:
    image: encodecmae
    container_name: encodecmae_decoder-train
    volumes:
      - /home/lpepino/encodecmaes/encodecmae:/workspace/encodecmae
      - /home/lpepino/encodecmaes/encodecmae_decoder:/workspace/encodecmae_decoder
      - /mnt/data:/workspace/datasets
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0','1']
            capabilities: [gpu]